import test from 'node:test';
import assert from 'node:assert/strict';
import { createProcessor } from '../pipeline.js';
import { VFile } from 'vfile';
import type { HeadingNode } from '../rehype-extract-headings.js';

const mockConfig = {
    port: 3000,
    host: '0.0.0.0',
    theme: 'nord',
    baseFile: 'README.md',
    storage: {
        default: 'local',
        providers: { local: { type: 'local' as const, basePath: '.' } },
        mounts: [],
        cache: { enabled: true, ttl: 300000, maxSize: 100 * 1024 * 1024 }
    }
};

test('outline extraction', async (t) => {
    const processor = createProcessor(mockConfig, () => true);

    await t.test('extracts headings without anchor hash', async () => {
        const content = '# Introduction\n\nSome text.\n\n## Section 1\n\nMore text.';
        const file = new VFile({ value: content });

        await processor.process(file);

        const headings = file.data.headings as HeadingNode[];

        assert.ok(headings, 'Headings should be extracted');
        assert.equal(headings.length, 2);

        assert.equal(headings[0].text, 'Introduction');
        // IDs are currently generated by rehypeSourceLines (e.g. L1), not rehypeSlug
        // assert.equal(headings[0].id, 'introduction');
        assert.match(headings[0].id, /^L\d+$/);

        assert.equal(headings[1].text, 'Section 1');
        assert.match(headings[1].id, /^L\d+$/);
    });

    await t.test('handles special characters in headings', async () => {
        const content = '# Hello World!';
        const file = new VFile({ value: content });

        await processor.process(file);

        const headings = file.data.headings as HeadingNode[];

        assert.equal(headings[0].text, 'Hello World!');
        // assert.equal(headings[0].id, 'hello-world');
        assert.match(headings[0].id, /^L\d+$/);
    });
});
