import { applyExportMediaPolicy, portableContentSecurityPolicy } from '../export-media.js';
import { EXPORT_CSS } from './export-css.js';

// Portable, static document export for the SPA. Content is already rendered by GlintRender.
// EXPORT_CSS is the real bundled theme CSS (generated by scripts/gen-export-css.mjs from
// the same set `glint-md render` uses) so exports match the live render — hiding KaTeX's
// MathML twin, the heading anchors, and sizing footnote refs (#146). Those layout rules
// key off the live shell classes, so the body mirrors the live wrapper.

function escapeHtml(value: string): string {
    return value.replace(/[&<>"']/g, (character) => ({
        '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
    }[character]!));
}

export function createStandaloneHtml(title: string, content: string, options: { allowRemoteMedia?: boolean } = {}): string {
    const safeContent = applyExportMediaPolicy(content, options.allowRemoteMedia);
    return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="${portableContentSecurityPolicy(options.allowRemoteMedia)}">
<title>${escapeHtml(title)}</title>
<style>${EXPORT_CSS}</style>
</head>
<body>
<main class="content"><div class="content-wrapper">
${safeContent}
</div></main>
</body>
</html>
`;
}
