import { applyExportMediaPolicy, portableContentSecurityPolicy } from '../export-media.js';
import { EXPORT_CSS } from './export-css.js';

// Portable, static document export for the SPA. Content is already rendered by GlintRender.
// EXPORT_CSS is the real bundled theme CSS (generated by scripts/gen-export-css.mjs from
// the same set `glint-md render` uses) so exports match the live render — hiding KaTeX's
// MathML twin, the heading anchors, and sizing footnote refs (#146). Those layout rules
// key off the live shell classes, so the body mirrors the live wrapper.

function escapeHtml(value: string): string {
    return value.replace(/[&<>"']/g, (character) => ({
        '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
    }[character]!));
}

// `extraCss` carries the live SPA's themes.css and the selected color-scheme override
// (#169); it follows EXPORT_CSS so its :root palette and [data-theme] rules win by
// cascade order. `theme` stamps the same root attribute applyTheme sets on the live doc.
export function createStandaloneHtml(title: string, content: string, options: { allowRemoteMedia?: boolean; extraCss?: string; theme?: string } = {}): string {
    const safeContent = applyExportMediaPolicy(content, options.allowRemoteMedia);
    const themeAttr = options.theme ? ` data-theme="${escapeHtml(options.theme)}"` : '';
    const extra = options.extraCss ? `\n<style>${options.extraCss}</style>` : '';
    return `<!doctype html>
<html lang="en"${themeAttr}>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="${portableContentSecurityPolicy(options.allowRemoteMedia)}">
<title>${escapeHtml(title)}</title>
<style>${EXPORT_CSS}</style>${extra}
</head>
<body>
<main class="content"><div class="content-wrapper">
${safeContent}
</div></main>
</body>
</html>
`;
}
